# Site settings
title: sharpDox
email: mail@geaz.de
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sharpdox.de" # the base hostname & protocol for your site
top_version_info_de: "1.0rc (September 2015)"
top_version_info_en: "1.0rc (September 2015)"
download_url: "https://github.com/Geaz/sharpDox/releases/download/v1.0rc/sharpDox.1.0rc.zip"
sharpDox_version: "1.0rc"

twitter_username: sharpDox
github_username:  Geaz

# Build settings
markdown: kramdown
